/* Auto-generated by snesrecomp v2 emit_bank. Do NOT hand-edit.
 *
 * Bank $A9. Each function below mutates the shared CpuState
 * struct via cpu->A / cpu->X / etc. Memory access goes through the
 * cpu_read{8,16} / cpu_write{8,16} helpers in cpu_state.h.
 */

#include <stdio.h>
#include <stdlib.h>

#include "cpu_state.h"
#include "cpu_trace.h"
#include "common_cpu_infra.h"
#include "funcs.h"


/* Forward declarations for in-bank entries. */
RecompReturn bank_A9_F585_M1X1(CpuState *cpu);
RecompReturn bank_A9_F585_M1X1(CpuState *cpu);

RecompReturn bank_A9_F585_M1X1(CpuState *cpu) {
  extern const char *g_last_recomp_func;
  g_last_recomp_func = "bank_A9_F585_M1X1";
  RecompStackPush("bank_A9_F585_M1X1");
  cpu_dbg_funcname("bank_A9_F585_M1X1");
  cpu_trace_func_entry(cpu, 0xA9F585, "bank_A9_F585_M1X1");
  RecompReturn _pending_skip = RECOMP_RETURN_NORMAL;
  (void)_pending_skip;  /* unused if no NLR site in this fn */
  uint16 _entry_s = cpu->S;
  uint8 _hrv = cpu->host_return_valid;
  if (cpu_take_tailcall_return_context(&_entry_s, &_hrv)) {
    cpu->host_return_valid = _hrv;
  }
  uint32 _host_return_pc24 = 0xFFFFFFFFu;
  if (_hrv == 2 || _hrv == 3) {
    uint16 _host_rpcl = cpu_read8(cpu, 0x00, (uint16)(_entry_s + 1u));
    uint16 _host_rpch = cpu_read8(cpu, 0x00, (uint16)(_entry_s + 2u));
    uint8 _host_rpb = (_hrv == 3) ? cpu_read8(cpu, 0x00, (uint16)(_entry_s + 3u)) : cpu->PB;
    _host_return_pc24 = ((uint32)_host_rpb << 16) |
        (uint16)((((_host_rpch << 8) | _host_rpcl) + 1u) & 0xFFFFu);
  }
  (void)_entry_s;  /* used by trampoline balance check */
  (void)_hrv;
  (void)_host_return_pc24;
  if (g_recomp_stack_top >= 1) g_cpu_entry_s[g_recomp_stack_top - 1] = _entry_s;
  L_F585_M1X1:
    cpu_trace_block(cpu, 0xA9F585);
    WatchdogCheck();
    cpu->cycles += 13;
    cpu->master_cycles += 13 * (g_memsel ? 6 : 8);
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += (g_memsel ? 6 : 8); }  /* D.l != 0 */
    uint8 _v1 = cpu_read8(cpu, cpu->DB, (uint16)(cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x001d))));
    uint16 _v2 = cpu_read_a16(cpu);
    uint8 _v3 = (uint8)(_v2 | _v1);
    cpu->_flag_Z = ((_v3) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v3) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v3));
    uint16 _v4 = cpu_read_a16(cpu);
    cpu_write8(cpu, cpu->DB, (uint16)(0x8282), _v4);
    { (void)cpu_trace_unresolved_goto_trap(cpu, 0xA9F585, 0xA9780F, "bank_A9_F585_M1X1", "L_780F_M1X1"); RecompStackPop(); return cpu_unresolved_abandon_balanced(cpu, 0xA9F585u, _entry_s, _hrv); } /* L_780F_M1X1 unresolvable cross-fn goto — target outside this bank's import range */
  RecompStackPop();
  return RECOMP_RETURN_NORMAL;
}


void bank_A9_F585(CpuState *cpu) {
  RecompReturn _r;
  switch (((cpu->m_flag & 1) << 1) | (cpu->x_flag & 1)) {
    case 0: _r = interp_tier_dispatch(cpu, 0xa9f585u); break; /* exact M0X0 LLE */
    case 1: _r = interp_tier_dispatch(cpu, 0xa9f585u); break; /* exact M0X1 LLE */
    case 2: _r = interp_tier_dispatch(cpu, 0xa9f585u); break; /* exact M1X0 LLE */
    case 3: _r = bank_A9_F585_M1X1(cpu); break;
    default: _r = interp_tier_dispatch(cpu, 0xa9f585u); break;
  }
  if (_r != RECOMP_RETURN_NORMAL) {
    fprintf(stderr,
      "[recomp] non-local-return SKIP_%d leaked past void alias %s\n",
      (int)_r, "bank_A9_F585");
    abort();
  }
}
