/* Auto-generated by snesrecomp v2 emit_bank. Do NOT hand-edit.
 *
 * Bank $30. Each function below mutates the shared CpuState
 * struct via cpu->A / cpu->X / etc. Memory access goes through the
 * cpu_read{8,16} / cpu_write{8,16} helpers in cpu_state.h.
 */

#include <stdio.h>
#include <stdlib.h>

#include "cpu_state.h"
#include "cpu_trace.h"
#include "common_cpu_infra.h"
#include "funcs.h"


/* Forward declarations for in-bank entries. */
RecompReturn bank_30_F010_M1X1(CpuState *cpu);
RecompReturn bank_30_F010_M1X1(CpuState *cpu);

RecompReturn bank_30_F010_M1X1(CpuState *cpu) {
  extern const char *g_last_recomp_func;
  g_last_recomp_func = "bank_30_F010_M1X1";
  RecompStackPush("bank_30_F010_M1X1");
  cpu_dbg_funcname("bank_30_F010_M1X1");
  cpu_trace_func_entry(cpu, 0x30F010, "bank_30_F010_M1X1");
  RecompReturn _pending_skip = RECOMP_RETURN_NORMAL;
  (void)_pending_skip;  /* unused if no NLR site in this fn */
  uint16 _entry_s = cpu->S;
  uint8 _hrv = cpu->host_return_valid;
  if (cpu_take_tailcall_return_context(&_entry_s, &_hrv)) {
    cpu->host_return_valid = _hrv;
  }
  uint32 _host_return_pc24 = 0xFFFFFFFFu;
  if (_hrv == 2 || _hrv == 3) {
    uint16 _host_rpcl = cpu_read8(cpu, 0x00, (uint16)(_entry_s + 1u));
    uint16 _host_rpch = cpu_read8(cpu, 0x00, (uint16)(_entry_s + 2u));
    uint8 _host_rpb = (_hrv == 3) ? cpu_read8(cpu, 0x00, (uint16)(_entry_s + 3u)) : cpu->PB;
    _host_return_pc24 = ((uint32)_host_rpb << 16) |
        (uint16)((((_host_rpch << 8) | _host_rpcl) + 1u) & 0xFFFFu);
  }
  (void)_entry_s;  /* used by trampoline balance check */
  (void)_hrv;
  (void)_host_return_pc24;
  if (g_recomp_stack_top >= 1) g_cpu_entry_s[g_recomp_stack_top - 1] = _entry_s;
  L_F010_M1X1:
    cpu_trace_block(cpu, 0x30F010);
    WatchdogCheck();
    cpu->cycles += 64;
    cpu->master_cycles += 512;
    uint16 _v1 = cpu_read_a16(cpu);
    cpu_write8(cpu, 0x00, (uint16)(cpu->S + 0x000d), _v1);
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    uint8 _v2 = cpu_read8(cpu, (uint8)((((((uint32)cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x000c) + 2)) << 16) | (uint32)cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x000c))) + (uint32)cpu->Y)) >> 16), (uint16)(((((uint32)cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x000c) + 2)) << 16) | (uint32)cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x000c))) + (uint32)cpu->Y)));
    uint16 _v3 = cpu_read_a16(cpu);
    uint8 _v4 = (uint8)(_v3 | _v2);
    cpu->_flag_Z = ((_v4) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v4) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v4));
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    uint8 _v5 = cpu_read8(cpu, cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x0070) + 2)), cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x0070)));
    uint16 _v6 = cpu_read_a16(cpu);
    uint8 _v7 = (uint8)(_v6 | _v5);
    cpu->_flag_Z = ((_v7) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v7) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v7));
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    uint8 _v8 = cpu_read8(cpu, cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x00f0) + 2)), cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x00f0)));
    uint16 _v9 = cpu_read_a16(cpu);
    uint8 _v10 = (uint8)(_v9 | _v8);
    cpu->_flag_Z = ((_v10) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v10) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v10));
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    uint8 _v11 = cpu_read8(cpu, cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x0074) + 2)), cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x0074)));
    uint16 _v12 = cpu_read_a16(cpu);
    uint8 _v13 = (uint8)(_v12 | _v11);
    cpu->_flag_Z = ((_v13) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v13) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v13));
    {
      uint16 _old_s = cpu->S;
      cpu_write8(cpu, 0x00, cpu->S, (uint8)(cpu->DB));
      cpu->S = (uint16)(cpu->S - 1);
      cpu_trace_stack_op(cpu, 0, CPU_STACK_OP_PHB, _old_s, -1);
    }
    cpu_trace_event(cpu, 0, CPU_TR_PHB, cpu->DB, cpu->DB);
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    {
      uint8 _m = cpu_read8(cpu, 0x00, (uint16)(cpu->D + 0x00fb));
      cpu->_flag_Z = ((_m & cpu->A) == 0) ? 1 : 0;
      cpu_write8(cpu, 0x00, (uint16)(cpu->D + 0x00fb), (uint8)(_m | cpu->A));
    }
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    uint8 _v14 = cpu_read8(cpu, 0x00, (uint16)(cpu->D + 0x00fb + cpu->X));
    {
      uint8 _bt = (uint8)((cpu->A & 0xFF) & (_v14 & 0xFF));
      cpu->_flag_Z = (_bt == 0) ? 1 : 0;
      cpu->_flag_N = (((_v14 & 0xFF) & 0x80) != 0) ? 1 : 0;
      cpu->_flag_V = (((_v14 & 0xFF) & 0x40) != 0) ? 1 : 0;
    }
    {
      uint8 _src_b = 0x83;
      uint8 _dst_b = 0xbb;
      uint8 _old_db = cpu->DB;
      cpu_trace_event(cpu, 0, CPU_TR_MVP, _src_b, _dst_b);
      cpu->DB = _dst_b;
      cpu_trace_db_change(cpu, 0x30f01fu, _old_db, _dst_b, CPU_TR_MVP);
      /* MVN/MVP always transfer at least one byte. A is count-minus-one,
       * and an interrupt resumes at this same opcode with the updated
       * A/X/Y/DB state. The block's static charge covers the first byte;
       * each repeated byte costs another seven CPU cycles. */
      do {
        uint8 _b = cpu_read8(cpu, _src_b, cpu->X);
        cpu_write8(cpu, _dst_b, cpu->Y, _b);
        cpu->X = (uint16)(cpu->X -1);
        cpu->Y = (uint16)(cpu->Y -1);
        if (cpu->x_flag) { cpu->X &= 0x00FFu; cpu->Y &= 0x00FFu; }
        cpu->A = (uint16)(cpu->A - 1);
        if (cpu->A != 0xFFFF) {
          if (interp_bridge_lle_master_deadline_reached(cpu)) {
    RecompStackPop();
            return interp_bridge_lle_yield_unwind(cpu, 0x30f01fu);
          }
          cpu->cycles += 7;
          cpu->master_cycles += 7 * 8;
        }
      } while (cpu->A != 0xFFFF);
    }
    uint8 _v15 = cpu_read8(cpu, cpu->DB, (uint16)(0x05a0));
    uint16 _v16 = cpu_read_a16(cpu);
    uint8 _v17 = (uint8)(_v16 | _v15);
    cpu->_flag_Z = ((_v17) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v17) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v17));
    if (cpu->D & 0xFF) { cpu->cycles += 1; cpu->master_cycles += 8; }  /* D.l != 0 */
    uint8 _v18 = cpu_read8(cpu, (uint8)((((((uint32)cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x00f8) + 2)) << 16) | (uint32)cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x00f8))) + (uint32)cpu->Y)) >> 16), (uint16)(((((uint32)cpu_read8(cpu, 0x00, (uint16)((uint16)(cpu->D + 0x00f8) + 2)) << 16) | (uint32)cpu_read16(cpu, 0x00, (uint16)(cpu->D + 0x00f8))) + (uint32)cpu->Y)));
    uint16 _v19 = cpu_read_a16(cpu);
    uint8 _v20 = (uint8)(_v19 & _v18);
    cpu->_flag_Z = ((_v20) == 0) ? 1 : 0;
    cpu->_flag_N = (((_v20) & 0x80) != 0) ? 1 : 0;
    cpu_write_a_m(cpu, (uint16)(_v20));
    cpu_trace_event(cpu, 0, CPU_TR_RTI, 0, 0);
    { cpu->S = (uint16)(cpu->S + 1); cpu->P = cpu_read8(cpu, 0x00, cpu->S); cpu_p_to_mirrors(cpu);
      cpu->S = (uint16)(cpu->S + 2);  /* pull + discard PC */
      if (!cpu->emulation) cpu->S = (uint16)(cpu->S + 1);  /* native: pull + discard PB */
      cpu_trace_px_record(cpu, 0, 3 /*RTI*/, cpu->P, cpu->P);
    RecompStackPop();
      return RECOMP_RETURN_NORMAL; /* RTI: popped interrupt frame */ }
  RecompStackPop();
  return RECOMP_RETURN_NORMAL;
}


void bank_30_F010(CpuState *cpu) {
  RecompReturn _r;
  switch (((cpu->m_flag & 1) << 1) | (cpu->x_flag & 1)) {
    case 0: _r = interp_tier_dispatch(cpu, 0x30f010u); break; /* exact M0X0 LLE */
    case 1: _r = interp_tier_dispatch(cpu, 0x30f010u); break; /* exact M0X1 LLE */
    case 2: _r = interp_tier_dispatch(cpu, 0x30f010u); break; /* exact M1X0 LLE */
    case 3: _r = bank_30_F010_M1X1(cpu); break;
    default: _r = interp_tier_dispatch(cpu, 0x30f010u); break;
  }
  if (_r != RECOMP_RETURN_NORMAL) {
    fprintf(stderr,
      "[recomp] non-local-return SKIP_%d leaked past void alias %s\n",
      (int)_r, "bank_30_F010");
    abort();
  }
}
